"""Tenant full lifecycle journey test.

Validates the complete tenant lifecycle:
  1. Create tenant via API
  2. Verify DB insertion with raw SQL
  3. Init schema (POST /init-schema — warns if endpoint not available)
  4. Update tenant
  5. List tenants and verify presence
  6. Delete via DELETE (hard delete)

Uses the ``client`` fixture which overrides get_current_user (auth bypassed)
so the test focuses on CRUD lifecycle, not authentication.
"""

from fastapi.testclient import TestClient
from sqlalchemy import text
from sqlalchemy.orm import Session

BASE_URL = "/api/v1/tenants"

TENANT_PAYLOAD = {
    "name": "Journey Test Firma s.r.o.",
    "ico": "87654321",
    "dic": "2087654321",
    "ic_dph": "SK2087654321",
    "address_street": "Testovacia 42",
    "address_city": "Bratislava",
    "address_zip": "81101",
    "address_country": "SK",
    "bank_iban": "SK8975000000000087654321",
    "bank_bic": "TATRSKBX",
    "default_role": "accountant",
    "is_active": True,
}


def test_tenant_full_journey(
    client: TestClient,
    db_session: Session,
):
    """End-to-end tenant lifecycle: create → verify DB → init schema → update → list → delete."""

    # ------------------------------------------------------------------
    # Step 1 — Create tenant
    # ------------------------------------------------------------------
    resp = client.post(BASE_URL, json=TENANT_PAYLOAD)
    assert resp.status_code == 201, f"Create failed: {resp.text}"

    data = resp.json()
    assert data["name"] == "Journey Test Firma s.r.o."
    assert data["ico"] == "87654321"
    assert data["is_active"] is True
    # schema_name generated by _generate_schema_name(name, ico) — see service layer
    schema_name = data["schema_name"]
    assert schema_name.startswith("tenant_"), f"schema_name should start with 'tenant_': {schema_name}"

    tenant_id = data["id"]

    # ------------------------------------------------------------------
    # Step 2 — Verify DB insertion via raw SQL
    # ------------------------------------------------------------------
    row = db_session.execute(
        text("SELECT id, ico, name, is_active FROM public.tenants WHERE id = :id"),
        {"id": tenant_id},
    ).fetchone()

    assert row is not None, "Tenant row not found in DB"
    assert row.ico == "87654321"
    assert row.name == "Journey Test Firma s.r.o."
    assert row.is_active is True

    # ------------------------------------------------------------------
    # Step 3 — Init schema
    # POST /api/v1/tenants/{id}/init-schema
    # ------------------------------------------------------------------
    init_resp = client.post(f"{BASE_URL}/{tenant_id}/init-schema")
    if init_resp.status_code not in (404, 405):
        assert init_resp.status_code == 200, f"Init schema failed: {init_resp.text}"
        # Verify schema existence in information_schema
        schema_row = db_session.execute(
            text("SELECT schema_name FROM information_schema.schemata WHERE schema_name = :sn"),
            {"sn": schema_name},
        ).fetchone()
        assert schema_row is not None, f"Schema '{schema_name}' not found after init"

    # ------------------------------------------------------------------
    # Step 4 — Update tenant
    # Router exposes PATCH for partial updates (per Router Generation Checklist).
    # ------------------------------------------------------------------
    update_payload = {
        "address_city": "Martin",
        "bank_bic": "SUBASKBX",
    }
    resp = client.patch(
        f"{BASE_URL}/{tenant_id}",
        json=update_payload,
    )
    assert resp.status_code == 200, f"Update failed: {resp.text}"

    updated = resp.json()
    assert updated["address_city"] == "Martin"
    assert updated["bank_bic"] == "SUBASKBX"
    # Unchanged fields should persist
    assert updated["name"] == "Journey Test Firma s.r.o."
    assert updated["ico"] == "87654321"

    # ------------------------------------------------------------------
    # Step 5 — List tenants and verify presence
    # ------------------------------------------------------------------
    resp = client.get(BASE_URL)
    assert resp.status_code == 200, f"List failed: {resp.text}"

    list_data = resp.json()
    assert "items" in list_data
    tenant_ids = [t["id"] for t in list_data["items"]]
    assert tenant_id in tenant_ids, "Created tenant not found in list"

    # ------------------------------------------------------------------
    # Step 6 — Delete tenant (DELETE → 204, hard delete)
    # ------------------------------------------------------------------
    resp = client.delete(f"{BASE_URL}/{tenant_id}")
    assert resp.status_code == 204, f"Delete failed: {resp.text}"

    # Verify deletion via raw SQL — router calls delete_tenant() (hard delete)
    row = db_session.execute(
        text("SELECT id FROM public.tenants WHERE id = :id"),
        {"id": tenant_id},
    ).fetchone()
    assert row is None, "Tenant row should be removed after DELETE (hard delete)"

    # ------------------------------------------------------------------
    # Cleanup — drop schema if it was created
    # ------------------------------------------------------------------
    db_session.execute(text(f"DROP SCHEMA IF EXISTS {schema_name} CASCADE"))
    db_session.commit()
